services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 10s
      retries: 15
    networks:
      - internal

  liquibase:
    build:
      dockerfile: database.dockerfile
    environment:
      - INSTALL_POSTGRES=true
    tty: true
    stdin_open: true
    networks:
      - internal
    depends_on:
      database:
        condition: service_healthy

  backend:
    build:
      dockerfile: backend.dockerfile
    ports:
      - 8080:8080
    networks:
      - internal
    depends_on:
      database:
        condition: service_healthy

networks:
  internal:
    name: internal
